# Generated by Django 3.2.13 on 2022-11-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='from_review',
        ),
    ]
