# Generated by Django 3.2.13 on 2022-11-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='represent',
        ),
        migrations.AddField(
            model_name='badge',
            name='isGet',
            field=models.BooleanField(default=False),
        ),
    ]
